# Generated by Django 2.2 on 2021-07-14 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('about', models.TextField()),
                ('established_date', models.DateTimeField()),
                ('contact_numbers', models.TextField()),
                ('emails', models.TextField(null=True)),
                ('avg_fees', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare_facility.Facility')),
                ('ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare_facility.Ownership')),
            ],
            options={
                'unique_together': {('facility', 'ownership')},
            },
        ),
        migrations.CreateModel(
            name='FacilityAffiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare_facility.Affiliation')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare_facility.Facility')),
            ],
            options={
                'unique_together': {('facility', 'affiliations')},
            },
        ),
    ]
