# Generated by Django 2.2 on 2021-07-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_facility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
