# Generated by Django 2.2 on 2021-07-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_facility', '0002_facility_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='pin_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
