# Generated by Django 2.2 on 2021-07-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_facility', '0003_auto_20210714_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.TextField(default='ashish'),
            preserve_default=False,
        ),
    ]
