# Generated by Django 2.2 on 2021-07-14 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_facility', '0004_auto_20210714_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='facility',
            name='city',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='facility',
            name='pin_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='facility',
            name='state',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='FacilitySpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare_facility.Facility')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare_facility.Speciality')),
            ],
            options={
                'unique_together': {('facility', 'speciality')},
            },
        ),
    ]
