# Generated by Django 2.2 on 2021-07-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_facility', '0005_auto_20210714_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityownership',
            name='name',
            field=models.TextField(default='name'),
            preserve_default=False,
        ),
    ]
